apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: rm565486-prd

namePrefix: prd-

commonLabels:
  environment: prd

images:
  - name: rm565486-app
    newName: PLACEHOLDER_ECR_URL/rm565486-app
    newTag: latest

patches:
  - path: patch-replicas.yaml
  - path: patch-env.yaml
