apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: rm565486-prd

namePrefix: prd-

commonLabels:
  environment: prd

images:
- name: rm565486-app
  newName: 826773401041.dkr.ecr.eu-central-1.amazonaws.com/rm565486-app
  newTag: 084491e98c3b0ae4fdad28380173dc4f7517b48b

patches:
- path: patch-replicas.yaml
- path: patch-env.yaml
