apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: rm565486-prd

namePrefix: prd-

commonLabels:
  environment: prd

images:
- name: rm565486-app
  newName: 826773401041.dkr.ecr.eu-central-1.amazonaws.com/rm565486-app
  newTag: 0e54adafd9ce0bd90f1414de19e6122ff6945f0f

patches:
- path: patch-replicas.yaml
