apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: rm565486-dev

namePrefix: dev-

commonLabels:
  environment: dev

images:
- name: rm565486-app
  newName: 826773401041.dkr.ecr.eu-central-1.amazonaws.com/rm565486-app
  newTag: 7f49e4b2d9ab582a04d15e326473c251d7275e00

patches:
- path: patch-replicas.yaml
- path: patch-env.yaml
