apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: rm565486-dev

namePrefix: dev-

commonLabels:
  environment: dev

images:
- name: rm565486-app
  newName: 826773401041.dkr.ecr.eu-central-1.amazonaws.com/rm565486-app
  newTag: d16f4f0d56a147dadd6c4f21340a2b99f6492cb2

patches:
- path: patch-replicas.yaml
- path: patch-env.yaml
