apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: rm565486-dev

namePrefix: dev-

commonLabels:
  environment: dev

images:
- name: rm565486-app
  newName: 826773401041.dkr.ecr.eu-central-1.amazonaws.com/rm565486-app
  newTag: 5c001c8de181f0a44c06ce1f59e5de7d8f448925

patches:
- path: patch-replicas.yaml
- path: patch-env.yaml
